version: 0.2

env:
  parameter-store:
    GIT_TOKEN: /mason.cahiill/demo/gittoken

phases:
  install:
    runtime-versions:
      ruby: 2.6
      docker: 18
    commands:
      - echo Installing Bundler...
      - gem install bundler
      - bundle install --with test
  pre_build:
    commands:
      - echo Running tests..
      - bundle exec rake demo:test
  build:
    commands:
      - bundle exec rake docker:build
  post_build:
    commands:
      - bundle exec rake coverage
