
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lab 9.2 SAM template to write to DynamoDb Table

Parameters:
  GitToken:
    Type: String
    Description: OAuth token for GitHub

Globals:
  Function:
    Runtime: ruby2.5
    Timeout: 30
    Environment:
      Variables:
        GIT_TOKEN: !Ref GitToken

Resources:

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .././lambda
      Handler: index.handler
      Policies:
        - AWSLambdaExecute
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:DeleteLogGroup
                - logs:DeleteLogStream
                - logs:PutLogEvents
              Resource: '*'

Outputs:
  LambdaArn:
    Description: Lambda Arn
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-LambdaArn
