AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Post CodeCoverage to Github pull request
Parameters:
  GitToken:
    Type: String
    Description: OAuth token for GitHub
Globals:
  Function:
    Runtime: ruby2.5
    Timeout: 30
    Environment:
      Variables:
        GIT_TOKEN:
          Ref: GitToken
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role:
        Fn::ImportValue: mcahill-build-CodeBuildRoleArn
      CodeUri: s3://masoncahilldemo/api/07f623c0d4a8f31097291e3830eb5a86
      Handler: index.handler
      Policies:
      - AWSLambdaExecute
      - AWSCodeBuildDeveloperAccess
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DeleteLogGroup
          - logs:DeleteLogStream
          - logs:PutLogEvents
          Resource: '*'
Outputs:
  LambdaArn:
    Description: Lambda Arn
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LambdaArn
