AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Post CodeCoverage to Github pull request
Parameters:
  GitToken:
    Type: String
    Description: OAuth token for GitHub
Globals:
  Function:
    Runtime: ruby2.5
    Timeout: 30
    Environment:
      Variables:
        GIT_TOKEN:
          Ref: GitToken
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      CodeUri: s3://masoncahilldemo/api/c8523adfc251a6216bc7f211ba063c22
      Handler: index.handler
      Policies:
      - AWSLambdaExecute
      - AWSCodeBuildDeveloperAccess
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:DeleteLogGroup
          - logs:DeleteLogStream
          - logs:PutLogEvents
          Resource: '*'
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: LambdaFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::ImportValue: mcahill-build-LambdaTriggerArn
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
            - lambda.amazonaws.com
            - events.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
      - PolicyName: CodeBuildAllow
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DeleteLogGroup
            - logs:DeleteLogStream
            - logs:PutLogEvents
            - lambda:Invoke*
            - lambda:Get*
            - events:PutRule
            - events:PutEvents
            - events:PutTargets
            - codebuild:BatchGetBuilds
            Resource: '*'
Outputs:
  LambdaArn:
    Description: Lambda Arn
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LambdaArn
