---
user: nobody
group: nobody
timeout: 30
wait: 30
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
chdir: /app
rackup: /app/config.ru
log: /app/thin.log
pid: /app/thin.pid
